In [1]:
from Mandas import Matrix, dot
import numpy as np

In [2]:
T = Matrix(np.array([[1,2,3], [4,5,6], [7,8,9]]))
T

[[1 2 3]
 [4 5 6]
 [7 8 9]]

# [bfs on adjacency matrix](https://arxiv.org/pdf/1906.03113.pdf)

In [15]:
M = Matrix([[0,0,0,1,0], 
            [0,0,0,0,1], 
            [0,0,0,1,1], 
            [1,0,1,0,0], 
            [0,1,1,0,0]])

In [16]:
c = np.array([0,1,0,0,0])  # we are in vertex 2

In [17]:
dot(M, c)  # and we will go to vertex 5

array([0, 0, 0, 0, 1])

In [18]:
# pop out 2 since we just visited
M.pop(2)

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]])

In [20]:
c = np.array([0,0,0,1])  # we are currently on vertex 5

In [21]:
dot(M, c)  # after dotting, we end up on vertex 3

array([0, 1, 0, 0])

In [22]:
# pop out 5 since we visited vertex 5
M.pop(5)

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [23]:
M

[[0 0 1]
 [0 0 1]
 [1 1 0]]

In [24]:
c = np.array([0,1,0])  # we are on vertex 3

In [25]:
dot(M, c)  # after dotting we end up on vertex 4

array([0, 0, 1])

In [26]:
# pop out 3 so we don visit it again
M.pop(3)

array([[0, 1],
       [1, 0]])

In [27]:
c = np.array([0,1])  # we're now on vertex 4

In [29]:
dot(M, c)  # we are now on vertex 1

array([1, 0])