In [1]:
from Mandas import Matrix, dot
import numpy as np

In [13]:
T = Matrix(np.array([[1,2,3], [4,5,6], [7,8,9]]))
T

[[1 2 3]
 [4 5 6]
 [7 8 9]]

# bfs implementation

In [76]:
M = Matrix([[0,0,0,1,0], 
            [0,0,0,0,1], 
            [0,0,0,1,1], 
            [1,0,1,0,0], 
            [0,1,1,0,0]])

In [77]:
M

Matrix(matrix=[[0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 1],
               [1, 0, 1, 0, 0], [0, 1, 1, 0, 0]])

In [78]:
c = np.array([0,1,0,0,0])

In [79]:
dot(M, c)

array([0, 0, 0, 0, 1])

In [80]:
# pop out 2
M.pop(2)

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]])

In [82]:
M

Matrix(matrix=array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]]))

In [83]:
c = np.array([0,0,0,1])

In [84]:
dot(M, c)

array([0, 1, 0, 0])

In [85]:
# pop out 5
M.pop(5)

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [86]:
M

Matrix(matrix=array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]]))

In [87]:
c = np.array([0,1,0])

In [88]:
dot(M, c)

array([0, 0, 1])

In [89]:
# pop out 3
M.pop(3)

array([[0, 1],
       [1, 0]])

In [90]:
M

Matrix(matrix=array([[0, 1],
       [1, 0]]))

In [91]:
c = np.array([0,1])

In [92]:
dot(M, c)

array([1, 0])

In [113]:
M.__dict__

{'matrix': array([[0, 1],
        [1, 0]]),
 'labels': {1: 0, 4: 1}}