In [92]:
import numpy as np

def dot(a, b):
    if isinstance(a, Matrix):
        a = a.value
    if isinstance(b, Matrix):
        b = b.value
    return np.dot(a, b)

class Matrix():
    def __init__(self, matrix):
        self.matrix = self.convert(matrix)
        _ = self.create_col(matrix)
        
    def convert(self, matrix):
        """convert list of lists into dictionary of lists. 
        """
        row_labels = {}
        for i, row in enumerate(matrix):
            row_labels[i + 1] = row  # 1 index not 0
        return row_labels
    
    def create_col(self, matrix):
        self.col_labels = {}  # k = matrix label, v = corresponding list position
        for i in range(len(matrix[0])):
            self.col_labels[i + 1] = i
        
    def pop(self, p):
        """remove row/col index from matrix.
        """
        if p not in self.matrix.keys():
            raise Exception('row does not exist')
        
        # remove row from matrix dict
        self.matrix.pop(p)
        
        # identify col idx to be removed
        idx_of_element_to_be_removed = self.col_labels[p]
        
        # remove the appropriate element from each row
        for k, v in self.matrix.items():
            v.pop(idx_of_element_to_be_removed)
            
        # update column labels
        self.col_labels.pop(p)  # remove from column label dictionary
        for k, v in self.col_labels.items():
            if k > p:
                self.col_labels[k] -= 1
            
                
    @property
    def value(self):
        """updated matrix in numpy form
        """
        # sort keys, which represent rows
        sorted_keys = sorted(self.matrix.keys())
        m = np.array([self.matrix[k] for k in sorted_keys])
        return m
    
    @property
    def labels(self):
        return list(self.matrix.keys())

In [93]:
M = Matrix([[0,0,0,1,0], 
            [0,0,0,0,1], 
            [0,0,0,1,1], 
            [1,0,1,0,0], 
            [0,1,1,0,0]])

In [108]:
c = np.array([0,1,0,0,0])

In [95]:
dot(M, c)

array([0, 0, 0, 0, 1])

In [96]:
# pop out 2
M.pop(2)

In [97]:
M.value

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]])

In [98]:
c = np.array([0,0,0,1])

In [99]:
dot(M, c)

array([0, 1, 0, 0])

In [100]:
# pop out 5
M.pop(5)

In [101]:
M.value

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [102]:
c = np.array([0,1,0])

In [103]:
dot(M, c)

array([0, 0, 1])

In [104]:
# pop out 3
M.pop(3)

In [105]:
M.value

array([[0, 1],
       [1, 0]])

In [106]:
c = np.array([0,1])

In [107]:
dot(M, c)

array([1, 0])

In [110]:
M.__dict__

{'matrix': {1: [0, 1], 4: [1, 0]}, 'col_labels': {1: 0, 4: 1}}