In [165]:
import inspect

class random(object):
    @classmethod
    def _get_param_names(cls):
        init = getattr(cls.__init__, 'deprecated_original', cls.__init__)
        init_signature = inspect.signature(init)
        return init_signature
    
    def __init__(self, foo):
        self.foo =foo

    def __repr__(self):
        na = self._get_param_names()
        return "hello"

In [166]:
r = random(2)

In [167]:
r._get_param_names()

<Signature (self, foo)>

In [170]:
r

hello

In [120]:
from sklearn.base import BaseEstimator, RegressorMixin
import numpy as np

def dot(a, b):
    if isinstance(a, Matrix):
        a = a.matrix
    if isinstance(b, Matrix):
        b = b.matrix
    return np.dot(a, b)


class Matrix(BaseEstimator):
    def __init__(self, matrix):
        self.matrix = matrix
        self.labels = self.create_labels(matrix)
        
    def create_labels(self, matrix):
        """
        k = matrix label, v = corresponding list position
        """
        labels = {}  
        for i in range(len(matrix[0])):
            labels[i + 1] = i
        return labels
        
    def pop(self, p):
        """remove row/col index from matrix.
        """
        if p not in self.labels.keys():
            raise Exception("row does not exist")
        
        # step 1: remove key from labels
        skip = self.labels[p]
        self.labels.pop(p)

        
        # step 2: update index position for everything that follows
        for k, v in self.labels.items():
            if k > p:
                self.labels[k] -= 1
        
        # step 3: recreate matrix with updated rows
        # https://stackoverflow.com/questions/10996140/how-to-remove-specific-elements-in-a-numpy-array
        self.matrix = np.array([list(np.delete(row, skip)) for i, row in enumerate(self.matrix) if i!= skip])
        return self.matrix
                

In [171]:
T = Matrix([[1,2,3], [4,5,6], [7,8,9]])
T

Matrix(matrix=[[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [172]:
T = Matrix(np.array([[1,2,3], [4,5,6], [7,8,9]]))
T

Matrix(matrix=array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]))

In [173]:
T.pop(3)

array([[1, 2],
       [4, 5]])

In [175]:
T

Matrix(matrix=array([[1, 2],
       [4, 5]]))

In [76]:
M = Matrix([[0,0,0,1,0], 
            [0,0,0,0,1], 
            [0,0,0,1,1], 
            [1,0,1,0,0], 
            [0,1,1,0,0]])

In [77]:
M

Matrix(matrix=[[0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 1],
               [1, 0, 1, 0, 0], [0, 1, 1, 0, 0]])

In [78]:
c = np.array([0,1,0,0,0])

In [79]:
dot(M, c)

array([0, 0, 0, 0, 1])

In [80]:
# pop out 2
M.pop(2)

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]])

In [82]:
M

Matrix(matrix=array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 0]]))

In [83]:
c = np.array([0,0,0,1])

In [84]:
dot(M, c)

array([0, 1, 0, 0])

In [85]:
# pop out 5
M.pop(5)

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [86]:
M

Matrix(matrix=array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]]))

In [87]:
c = np.array([0,1,0])

In [88]:
dot(M, c)

array([0, 0, 1])

In [89]:
# pop out 3
M.pop(3)

array([[0, 1],
       [1, 0]])

In [90]:
M

Matrix(matrix=array([[0, 1],
       [1, 0]]))

In [91]:
c = np.array([0,1])

In [92]:
dot(M, c)

array([1, 0])

In [113]:
M.__dict__

{'matrix': array([[0, 1],
        [1, 0]]),
 'labels': {1: 0, 4: 1}}